### ISSUE TITLE
Curry Favor

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1183]
![image](https://user-images.githubusercontent.com/31585532/33204862-bb7637d0-d0fc-11e7-8927-965c219c6cdd.png)

**Comment by SnarkAttack** [comment]
I'll grab this one. Since there's no better way to communicate on Github, is it possible to be made a collaborator? I really just want to be able to self-assign tasks and add appropriate labels to my pull requests. Having to open up every card issue to see if I commented I worked on it isn't much fun.
