### ISSUE TITLE
Endless Plains

### ISSUE THREAD

**Issue by mikallo** [gryffon/ringteki#1217]
Endless Plains reaction broke the province but did not cause my opponent to discard an attacking character. He was attacking with a lone Unassuming Yojimbo ally with 1 fate on it no attachments (He was a lion player with the scorpion splash). I did not assign any defenders.

**Comment by jeremylarner** [comment]
I'm guessing this is because your opponent just clicked cancel when the game prompted him to choose a character to discard.  I've been reluctant to remove the buttons to cancel targeting for abilities, but maybe this issue is becoming widespread enough that this is something we should look at doing.
