### ISSUE TITLE
Site is not secure

### ISSUE THREAD

**Issue by IMABUNNEH** [gryffon/ringteki#146]
Get yourself a good HTTPS certificate it's not difficult to do and since you're collecting logins/passwords it's incredibly irresponsible to have not done so already.

**Comment by elstob** [comment]
@IMABUNNEH - You're correct that this is a requirement. However the site you are referring to is a development server that is not officially launched yet. Unless you're offering to pay for the cert yourself I suggest you exercise some patience and civility to the people who are spending their free time to build a game for you out of their own pocket.

**Comment by IMABUNNEH** [comment]
I mean you can be a cunt all you want, but there's NOTHING on the site to tell anyone it's still considered in Development. Not anywhere at all, meaning anyone who arrives at it (say by the linking to it plenty of people have already done) they will not be under the impression that it is still in development, or still in beta. 

And the fact remains you're still allowing people to register usernames and passwords without securing the site and without MAKING IT CLEAR to the average user that the site isn't secure. So call me impatient or rude if you want, but the site needs securing or it needs to be made very clear to people that they're submitting login information through an unsecure connection, and acting like it's MY problem is out of order.

**Comment by elstob** [comment]
@IMABUNNEH The first thing I did was agree with you about the need for security before asking you to maybe check your sense of entitlement while raising it. If you can't comprehend that a small group of people working in their spare time might have different priorities to yours then I don't know how to help you. Nobody is making people sign up to an unsecured website linked to them by other people they probably do not know.

As an aside the hostile tone of your initial post and your need to reply with offensive language makes me feel bad for those that have to deal with you on a daily basis. You come across as the type of nerd who others have to abide in order to enjoy their hobby. Please enjoy the rage boner you'll undoubtedly get from wasting a few minutes of my day.

**Comment by IMABUNNEH** [comment]
So I assume you're going to make it clear to your users that they aren't currently submitting information securely? If you're willing to take public logins should we assume users details are at bare minimum hashed, or are you storing them in plaintext?

The disregard you show for the security of people using the site, and personal attacks in response to very valid security questions/concerns do not make you sound like you're giving up your time for the love of the game/community. If you loved the community enough to give up your free time towards development, you'd actually care about them exposing their information online.

**Comment by IMABUNNEH** [comment]
So having dug through the source code, I can see at least that passwords are stored hashed.

However since they're being sent from the frontend to backend in plaintext, over HTTP, there's still a pretty critical flaw. I know certificates cost money, but it's imperative that if you can't currently protect your users, then you should at least be warning them that they're not protected.

A simple (but clear) warning until then about the lack of security isn't exactly the worst thing in the world to ask for.

**Comment by IMABUNNEH** [comment]
Also I'm not sure how cost is an issue for you, you can get free HTTPS certificates here: https://letsencrypt.org/

**Comment by elstob** [comment]
My contributions so far have amounted to nothing more than editing a README. I'll jump in when my job affords me the time to do so. Either way I doubt I'll be getting access to any boxes to add/manage certs any time soon.

I'll tag @gryffon to flag Let's Encrypt which is a good suggestion. I was merely trying to highlight that your comment stating that he was being "incredibly irresponsible" was at best enthusiastically misguided and at worst insultingly rude given the context.

Finally is seems that you had the time and the domain knowledge to dig into the source code and identify that the passwords are stored with a hash. Therefore it should be easy for someone that smart, community minded and security motivated to add that warning and create the requisite pull request. Hooray for open source projects right?

**Comment by gryffon** [comment]
There's definitely going to be an SSL cert added for the actual site. This is a development server that I threw up and didn't actually advertise a whole lot. I'll throw up some text in the news reminding people that it's not an SSL secured site.

Eventually, we'll also likely be move user authentication to move an auth service. Likely Metagame.cards, which is what fiveringsdb uses(which will also allow access to a users private decks, instead of just public).

**Comment by gryffon** [comment]
SSL is active on the beta site now.
