### ISSUE TITLE
Spies at Court -> Done Button

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#1629]
Would it be possible to have it so that if someone hits the "done" button on the "Spies at Court" prompt without selecting anything it discards the two cards in a random order?

Much like clicking "done" during the fate phase doesn't skip over discarding people with no fate, clicking done on "spies at court" shouldn't skip over the discard.

**Comment by jeremylarner** [comment]
I currently have a fix on our development branch which removes the done button altogether for SaC (and a lot of other mandatory selections).  So that will solve the problem when it gets to the server in a sense, because it will force the player to choose an order.

Should there be a done button do order randomly?  I'm not sure - I think in the fate phase it's fine because there could be a lot of characters, and players get used to that dialog (they see it a lot).  At the moment, SaC is the only random multidiscard.  If they print another card which does more than 2 random discards, I'll review it.
