### ISSUE TITLE
Akodo Gunsō entering play effect and fate

### ISSUE THREAD

**Issue by akodophocea** [gryffon/ringteki#2158]
Hello,
There is a problem with the "Akodo Gunsō" card.

Following the update of the references rules (version 1.2 to 1.4), we place the fate AFTER that character enter play (page 7 - Fate). [https://images-cdn.fantasyflightgames.com/filer_public/40/4b/404b1a27-e7b5-4bef-a76d-ad0fed96d91b/l5c01-online_rulesreference_v14.pdf](url)

When the Akodo Gunsō enters play from a province, its reaction triggers (effect of coming into play) THEN it is possible to place fate on the Akodo Gunsō.

But every time I bring the Akodo Gunsō in play into play, Jigoku asks first if I want to put fate on it, then I can trigger the effect of the character.

This can have a lot of impact on the dynasty phase,

Thank you for your help,

akodophocea

**Comment by jeremylarner** [comment]
I don't agree with your interpretation of the rules.  Placing fate is part of the same framework event as playing the character, and so placement of fate happens before any reactions to playing that card or it coming into play can take place.  

It's true that jigoku does ask you to place fate before the card actually comes into play, but because there is no new information or possible change in game state that can occur between when your asked to make that choice and when the fate is actually placed, I don't think this is a problem.
