### ISSUE TITLE
Bayushi's Whisperers test failing

### ISSUE THREAD

**Issue by jamesoddy** [gryffon/ringteki#2559]
I've written a test for Bayushi's Whisperers that is failing.

commit available here ba2102f70e58da549859070a922883d3bc38ff1f

Pretty sure that BW is not prompting for a card name after the opponents hand is shown.  I'm not experienced enough with the card implementations yet, but I believe the intention is to show a prompt with the cards revealed from hand and allow one to be chosen.

Also, BW is not limited to naming a card that is revealed from the hand (rulings: https://fiveringsdb.com/card/bayushi-s-whisperers) so suggest that an "Other" option is given that shows a message to name a card in chat that must be manually adhered to (unless there is some way we could implement naming any card??).

Despite all this - it is only Bayushi's whisperers so I doubt anyone is playing it so probably not a major priority.

**Comment by jeremylarner** [comment]
Bayushi's whisperers gives players a text box to fill in (very similar to the one used in the deck builder), so your test looking for menu buttons will fail (because there aren't any).  If you want to write a test for it, you need to write something in the player interaction wrapper which simulates the message received from the client with the card name entered.

If it's not working on live, the reason is likely that @gryffon hasn't rebuilt the client. It may require a lobby restart, I'm not sure (we need to do one for Support of the Scorpion anyway).

**Comment by jamesoddy** [comment]
Figured it must be something like that.  I will take another look.  Thanks.

**Comment by jamesoddy** [comment]
I've had another look, pretty sure it is not coming up with a prompt at all:

![bayushi-s-whisperers](https://user-images.githubusercontent.com/958931/47239830-49d9a180-d3de-11e8-8941-04c096ea2a18.gif)

The hand is revealed to the log and then it just moves to the next action.  I've tried a few things to get it working, but cannot work it out - any ideas?  @jeremylarner 

This is from effectively the develop HEAD.

**Comment by jeremylarner** [comment]
Thanks, it looks like one of the changes I made for Kitsuki Shomon broke Whisperers.  It should look like this:
![image](https://user-images.githubusercontent.com/31585532/47254958-de84e380-d460-11e8-902c-c690d2167114.png)
