### ISSUE TITLE
Mantra of Water Doesn't Trigger

### ISSUE THREAD

**Issue by ulzeta** [gryffon/ringteki#2635]
Playing as Dragon with Phoenix Splash. The role is Support of the Phoenix. The opponent chooses the Water Ring but Mantra of Water doesn't trigger.

**Comment by jamesoddy** [comment]
We are missing a test for Mantra of Water, so I will look to write one of those. Can anyone else confirm if this is working/not working for them? I will try and replicate.

**Comment by xWorkerBeex** [comment]
Mantra of Water needs a bowed monk, otherwise it can't be activated. Works as intended for me.

**Comment by jamesoddy** [comment]
As xWorkerBeex mentioned, you need a bowed monk for Montra of Water to be triggered.  This is because the targeting rules https://fiveringsdb.com/rules/reference#target require that the target be affected by the effect.  In this case the "ready that character".  If the monk is not bowed then it cannot be chosen as a target and therefore the event cannot be triggered (even if you want to trigger it just for the "Draw 1 card" effect).

Reports are that this is working ok, please let us know if you have a specific scenario where it is definitely not working.

Also needs a test to confirm that it is working ok.

**Comment by ulzeta** [comment]
Yes, it is a misunderstanding on my part. Thank you.
