### ISSUE TITLE
MotC - Kakita Favorite

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2902]
![image](https://user-images.githubusercontent.com/31585532/52865734-2f69c780-3135-11e9-906c-819dcda48f93.png)

**Comment by siowyisheng** [comment]
i'll take this simple one

**Comment by jamesoddy** [comment]
@siowyisheng You picked this up a while ago, let me know if you need any help with it or how to get your implementation into a PR so we can take a look at it.

Otherwise, someone may need to take a look as the pack will be released soon (we have plenty of other cards to be getting on with though so no immediate rush!)

**Comment by siowyisheng** [comment]
I should be able to get it done soon. Will sound out by this weekend if I can't.

**Comment by jamesoddy** [comment]
Great.  Thanks for the quick reply.  Are you on the discord server?

**Comment by siowyisheng** [comment]
Yea but usually in uni chat. What channel are you guys on?

**Comment by jamesoddy** [comment]
It's a separate server for dev chat: https://discord.gg/jvmsrA (this invite expires in 1 day)

**Comment by jamesoddy** [comment]
Just in case you need it, this is a permanent invite link: https://discord.gg/tMzhyND
