### ISSUE TITLE
Iaijutsu Master triggerable from draw bid

### ISSUE THREAD

**Issue by naesseth** [gryffon/ringteki#2920]
Jigoku gave me the option to trigger Iaijutsu Master during the bid for cards during draw step. I didn't try to do it so I'm not sure what would've happened, but it stopped play and indicated that i could trigger it.

**Comment by jamesoddy** [comment]
Thanks for the report (and apologies for the late reply).

This was probably due to a duel being canceled (by Stay Your Hand) and the duel not being correctly "removed" from the game.  This was fixed when the duel refactor was deployed.  If you still have problems please open a new issue and I will close this one.
