### ISSUE TITLE
Chisei District

### ISSUE THREAD

**Issue by DojiHoe** [gryffon/ringteki#2971]
Chisei District is not active.  It does not stop an opponent from declaring a military conflict on the province it is located on.

**Comment by jamesoddy** [comment]
Thanks for the report - I've managed to replicate your issue.  This only happens if you change to political **after** you have chosen the province to attack.

The declaration of conflicts is slightly broken as it will allow you to change selections of conflict type and ring after you have selected the province and chosen covert targets etc.  This is actually causing a problem with a number of cards (Zokojin for example).  The whole declaration needs a bit of a re-work that we will get to at some point.  Thanks for the report.

**Comment by jamesoddy** [comment]
Conflict declaration has been refactored and is now live (PR #3135) that should fix this issue.
