### ISSUE TITLE
Social Puppeteer not displaying properly

### ISSUE THREAD

**Issue by TimeZeroX** [gryffon/ringteki#3247]
It's the only card since the release of Children of the Empire that is not displaying properly. The card works as intended though, it is not displaying its image.

![image](https://user-images.githubusercontent.com/50306904/58782804-74631e00-85ad-11e9-8379-beb8e96b5051.png)

**Comment by jamesoddy** [comment]
Can't get this error myself - can you please double check and make sure that you force a refresh (Ctrl + F5).

**Comment by TimeZeroX** [comment]
I did multiple CTRL+F5, no success
I logged out and I cleaned my cookies, no success
I tried to see it in the deckbuilding part, still no success

![image](https://user-images.githubusercontent.com/50306904/59569137-3e18aa80-9053-11e9-822d-39260e5ab72b.png)

**Comment by jamesoddy** [comment]
I would suggest that it is your client that is blocking the image - you have a ERR_BLOCKED_BY_CLIENT message.  It is likely an extension (such as an ad blocker) you have installed that is blocking it possibly because of the mention of "social" in the path.

Please try disabling any extensions you have and I expect you will find the culprit and then either disable that extension of it allows you to whitelist the path/domain.

**Comment by TimeZeroX** [comment]
Good catch. Adblocker was the culprit. I whitelisted Jigoku and it's fine now. :)
