### ISSUE TITLE
Hand real estate

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#356]
![image](https://user-images.githubusercontent.com/32277970/31392672-e13a5776-ada7-11e7-856c-99ecb4c1460b.png)

If you hand size gets large, the cards get really smashed together.  However, there is a bunch of non-utilized space on the right.  The hand appears that it has the room to spread out a bit and is more smashed than it needs to be.

**Comment by gryffon** [comment]
Odd. I'll check into that, it has an algorithm for determining the squish
factor, but it may be use a different value than the total window length,
since it was a ported feature.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jeremylarner** [comment]
Fixed by #435
