### ISSUE TITLE
Server state error after playing Banzai!

### ISSUE THREAD

**Issue by lufia22** [gryffon/ringteki#608]
I've received this error twice now after using Banzai's effect two times. It seems to correctly add the first activation, but the second activation is not added and the following error is displayed in chat:

> A Server error has occured processing your game state, apologies. Your game may now be in an inconsistent state, or you may be able to continue. The error has been logged.

**Comment by jeremylarner** [comment]
Yeah, I'm pretty sure it means one of the players in your game has at least one copy of Hida Kisada in their deck.  Kisada doesn't like Banzai, because it's second resolution doesn't follow the normal rules of the game, and I didn't think about it when I was scripting Kisada.  I've submitted a fix already though, so it should be resolved with the next server restart.
