### ISSUE TITLE
Air Ring for 2 honor not working 

### ISSUE THREAD

**Issue by TLFJ** [gryffon/ringteki#655]
Twice in one game, after winning the air ring, selecting "Gain 2 honor", I did not receive any additional honor.

Context:
Coincidentally, both times I had a "Blackmail Artist' Present, which triggers before the air ring, so perhaps it is related?

**Comment by jeremylarner** [comment]
Thanks for the report. I can't replicate any error with Air Ring. Blackmail Artist was bugged, and was doing the honor transfer the wrong way.  If you'd told me that it was taking honor that wasn't working, I'd have just put it down to that, but even if we take that out, you should have gained 1 (and your opponent also gained 1).  Maybe you didn't notice because you were focused on whether you honor is higher or lower than your opponent?

I'm going to close this, but if you see the same bug again, and can give me more details of what was happening (and a screenshot if possible), please report it again.
