### ISSUE TITLE
Seeker of Knowledge Bug

### ISSUE THREAD

**Issue by ZesuShadaban** [gryffon/ringteki#695]
While playing a game against Reiga, we encountered an issue when I played a Seeker of Knowledge from my hand into the active conflict. I played the card with 1 fate on it, and the fate was deducted from my fate pool. However, the card did not have any fate on it when it went into play into the conflict. The card was bordered with yellow instead of red, and I could not select it for any automated effects or manual commands. Other cards such as For Shame! could not be played off the Seeker of Knowledge as a card or from its keywords, as it was treated as not part of the conflict. When the conflict was resolved, it did not count towards my skill total and did not bow, nor could I bow it manually.

**Comment by jeremylarner** [comment]
This bug is weird - it seems to be caused by the game for some reason thinking that one of the spectators has played the card rather than the owner of that card.  I've refactored the conflict character code in an attempt to fix this, but please let me know if you (or anyone else) sees this again.  I have a couple of other ideas of how we might stop it, but I'd like to see if this one works first.
