### ISSUE TITLE
Young Rumonmonger is asked for reaction only once after using Shameful Display.

### ISSUE THREAD

**Issue by Sliski** [gryffon/ringteki#727]
When I control Young Rumonmonger, and opponen use Shameful Display, I'm asked for reaction only once instead of 2 times (assuming I passed 1st oportunity).

**Comment by dodgepong** [comment]
All triggered abilities are limit once per round unless otherwise stated, so this sounds like correct behavior to me, unless you didn't use the interrupt the first time you were presented with it.

**Comment by Sliski** [comment]
I updated description. I was thinking about the case, where I do not use the interrupt for honor, I'm not asked to interrupt dishonor.

**Comment by jeremylarner** [comment]
Yeah, this is a known issue.  I think it's an error in the prompt - both sides of Shameful display share an interrupt window, so the game should ask you whether you want to use it for either, and then which effect you're interrupting.  When you click pass, the game interprets that as you don't want to use it.

Thanks for the report - the fix for this isn't straightforward, but I'll have a look.

**Comment by jeremylarner** [comment]
This should be fixed now #739
