### ISSUE TITLE
Crab: Witch Hunter bug - only targets self

### ISSUE THREAD

**Issue by Dandelionsteam** [gryffon/ringteki#735]
Witch hunter action only allows himself as target for sacrifice

**Comment by jeremylarner** [comment]
I can't replicate this - what other characters did you have in play?

**Comment by Dandelionsteam** [comment]
a bowed hida guardian and vengeful berseker.

**Comment by Dandelionsteam** [comment]
tried playing again, using steadfast witch hunter. this time it only asked
me to click once.
click 1 for activation
click 2 for sacrifice
then it auto readied the witch hunter...

but i can select other characters now :) maybe my internet is messed up T_T

**Comment by jeremylarner** [comment]
You should get a prompt asking you what card you want to unbow first, then a prompt asking you which card you want to sacrifice.  You should also have a button which allows you to choose the cost first, but it doesn't appear at the moment due to a bug. 

It sounds like there might be a problem, I'll have a look at it.

**Comment by Dandelionsteam** [comment]
i got a prompt now asking to pay cost first :) steadfast witch hunter works
great again :) thank you so much :D if i only know how to code T_T
